M48
; DRILL file {KiCad 6.0.5-a6ca702e91~116~ubuntu20.04.1} date Sa 04 Jun 2022 17:59:48 CEST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-04T17:59:48+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.5-a6ca702e91~116~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1181
%
G90
G05
T1
X2.2654Y-3.998
T0
M30
